### ISSUE TITLE
Need README.

### ISSUE THREAD

**Issue by hsluoyz** [casbin/dart-casbin#8]

**Comment by MrUnfunny** [comment]
Hi @hsluoyz,
Since the library is currently a work in progress, I think the Readme can be like [lua-casbin](https://github.com/casbin/lua-casbin). This way it will be independent of dart specific code and will provide information about Casbin in general. If this approach looks fine to you, I can send a PR for updating Readme.

**Comment by hsluoyz** [comment]
@KNawm
